# Ezt a kódot Illessze be a 04_ipv6_worm_protection.sh fájlba!
#!/usr/bin/env bash
# 04_ipv6_worm_protection.sh
# IPv6 "v6worms" protection (sysctl + ip6tables)
# Implements mitigations inspired by Bellovin/Cheswick/Keromytis (v6 worm strategies).

set -euo pipefail

# ⚙️ KONFIGURÁCIÓ
SYSCTL_CONF="/etc/sysctl.d/99-ipv6-worms.conf"
SCRIPT_NAME="04_IPV6WORM" # KRITIKUS JAVÍTÁS: Szkriptszám korrekció
CRITICAL_FILES=("$SYSCTL_CONF") # Fájlok listája, amit a rollbacknek fel kell oldania.

# Fájlútvonalak
IP6TABLES_BIN="/sbin/ip6tables"
IP6TABLES_SAVE="/sbin/ip6tables-save"
IP6TABLES_RESTORE="/sbin/ip6tables-restore"
BACKUP_DIR="/var/backups/skell_backups/$SCRIPT_NAME"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"

# Paraméterek
DRY_RUN=true
IFACE="wlo1" # KRITIKUS JAVÍTÁS: Statikus interfész használata a 03-as szkripttel összhangban
ALLOW_RA=false # Engedi-e a Router Advertisement-et

# --- LOG ÉS HELPERS ---
log() {
    local level="$1"; shift
    local msg="$*"
    printf "%s [%s/%s] %s\n" "$(date +"%Y-%m-%d %H:%M:%S")" "$SCRIPT_NAME" "$level" "$msg"
}

run() {
    if $DRY_RUN; then
        log "DRY" "$*"
    else
        log "ACTION" "$*"
        "$@"
    fi
}

# --- TRANZAKCIÓS TISZTÍTÁS (BRANCH_CLEANUP) ---
function branch_cleanup() {
    log "FATAL" "Hiba történt a $SCRIPT_NAME futása közben! Rollback indítása..."

    # Fájlok feloldása a CRITICAL_FILES listából (Zero-Trust Rollback)
    for file in "${CRITICAL_FILES[@]}"; do
        if command -v chattr &> /dev/null && [ -f "$file" ]; then
            log "INFO" "-> Feloldás: chattr -i $file"
            chattr -i "$file" 2>/dev/null || true
        fi
    done

    # Sysctl backup visszaállítása
    if [ -f "$BACKUP_DIR/99-ipv6-worms.conf.bak" ]; then
        log "INFO" "-> Sysctl fájl visszaállítása a backupból."
        mv "$BACKUP_DIR/99-ipv6-worms.conf.bak" "$SYSCTL_CONF" || true
    fi

    # ip6tables backup visszaállítása (ha létezik)
    if [ -f "$BACKUP_DIR/ip6tables.before.$TIMESTAMP" ]; then
        log "INFO" "-> ip6tables szabályok visszaállítása a backupból."
        $IP6TABLES_RESTORE < "$BACKUP_DIR/ip6tables.before.$TIMESTAMP" 2>/dev/null || true
    fi

    log "FATAL" "$SCRIPT_NAME rollback befejezve. Kézi ellenőrzés szükséges!"
    exit 1
}
trap branch_cleanup ERR
# ---------------------------------------------------------------------------

# --- ARGUMENTUMOK FELDOLGOZÁSA ---
usage() {
  cat <<EOF
Usage: $0 [--iface IFACE] [--apply|--dry-run] [--allow-ra]
  --iface IFACE : target interface for per-interface sysctl rules (default: wlo1)
  --dry-run   : show planned changes (default)
  --apply     : make changes (writes sysctl + runs ip6tables-restore)
  --allow-ra  : allow accepting Router Advertisements on the IF (default: blocked for security)
EOF
  exit 1
}
# ---------------------------------------------------------------------------
# 0. ELŐKÉSZÍTÉS ÉS BEMENET ELLENŐRZÉSE
# ---------------------------------------------------------------------------

MODE="${1:---dry-run}" # Kezdő érték beállítása
DRY_RUN=true # Alapértelmezett beállítás

while [ $# -gt 0 ]; do
  case "$1" in
    --iface) IFACE="$2"; shift 2;;
    --apply) DRY_RUN=false; shift;;
    --dry-run) DRY_RUN=true; shift;;
    --allow-ra) ALLOW_RA=true; shift;;
    -h|--help) usage;;
    *) log "[ERROR] Unknown arg: $1"; usage;;
  esac
done

# root check
[ "$(id -u)" -eq 0 ] || { echo "Run as root"; exit 2; }

if $DRY_RUN; then
    log "INFO" "Mode: DRY-RUN (szimuláció)"
fi

# KRITIKUS JAVÍTÁS: Autodetect eltávolítva, IFACE=$IFACE (wlo1) használatban.
if [ -z "$IFACE" ]; then
    log "[ERROR] Interface not set. Use --iface IFACE or check default value." >&2
    exit 3
fi

log "START: IPv6 Worm Protection Flow. Interface: $IFACE. Mode: $(if $DRY_RUN; then echo "DRY-RUN"; else echo "APPLY"; fi)"


# ---------- Build sysctl content ----------
# KRITIKUS JAVÍTÁS: Stabilabb string hozzárendelés a set -e hibák elkerülésére
SYSCONF_CORE=$(cat <<'EOF'
# IPv6 worm protection sysctl (generated by 04_ipv6_worm_protection.sh)
# Global kernel hardening
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0
net.ipv6.conf.all.forwarding = 0
net.ipv6.conf.default.forwarding = 0
# limit ICMPv6 (kernel-level ratelimiting where available)
net.ipv6.icmp.ratelimit = 100
# protect ND tables a bit (not perfect but helpful)
net.ipv6.neigh.default.gc_thresh1 = 128
net.ipv6.neigh.default.gc_thresh2 = 512
net.ipv6.neigh.default.gc_thresh3 = 1024
# filesystem / kernel protections (useful generally)
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
kernel.dmesg_restrict = 1
kernel.kptr_restrict = 1
EOF
)

SYSCONF="$SYSCONF_CORE"$'\n'
# Add per-interface choices for RA/autoconf depending on --allow-ra
if $ALLOW_RA; then
  SYSCONF="$SYSCONF"$'\n'"# Allow RA on $IFACE (explicit because --allow-ra passed)"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.accept_ra = 1"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.autoconf = 1"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.accept_ra_defrtr = 1"
else
  SYSCONF="$SYSCONF"$'\n'"# Block Router Advertisements and autoconf on $IFACE by default (safer mitigation)"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.accept_ra = 0"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.autoconf = 0"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.accept_ra_defrtr = 0"
fi

# Additional per-interface privacy/enforcement
SYSCONF="$SYSCONF"$'\n'"# Prefer temporary (privacy) addresses on IF"
SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.use_tempaddr = 2"


# ---------- Build ip6tables rule set (Restore syntax) ----------
build_ip6_rules() {
  cat <<'RULES'
# Generated by 04_ipv6_worm_protection.sh
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]

# Loopback
-A INPUT -i lo -j ACCEPT

# Established connections
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow Neighbor Discovery ICMPv6 types (rate-limited)
-A INPUT -p ipv6-icmp --icmpv6-type 133 -m limit --limit 30/min -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type 134 -m limit --limit 30/min -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type 135 -m limit --limit 100/min -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type 136 -m limit --limit 100/min -j ACCEPT

# Allow essential ICMPv6 error messages
-A INPUT -p ipv6-icmp --icmpv6-type destination-unreachable -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type packet-too-big -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type time-exceeded -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type parameter-problem -j ACCEPT

# Block non-ND multicast traffic arriving to the interface (drop other ff00::/8)
-A INPUT -d ff00::/8 -i __IFACE__ -p ! ipv6-icmp -j DROP

# KRITIKUS JAVÍTÁS: Quad9 DNS szabályok eltávolítva (Redundancia / VPN)

# Log a small amount and drop the rest
-A INPUT -m limit --limit 5/min -j LOG --log-prefix "V6WORMDROP: "
-A INPUT -j DROP
COMMIT
RULES
}

IP6_RAW=$(build_ip6_rules)
IP6_RENDERED=$(printf "%s" "$IP6_RAW" | sed "s|__IFACE__|$IFACE|g")


# ----------------------------------------------------
# DRY-RUN FÁZIS
# ----------------------------------------------------
if $DRY_RUN; then
    log "START: $SCRIPT_NAME flow (DRY-RUN MODE)"

    log "INFO" "Sysctl konfiguráció kiírása a $SYSCTL_CONF fájlba (IPv6 worm mitigation + kernel hardening)."
    log "===== SYSCTL (will be written to: $SYSCTL_CONF) ====="
    echo "$SYSCONF" | sed 's/^/  /'
    run "sysctl --system"

    log "INFO" "ip6tables szabályok mentése $BACKUP_DIR alá."
    run "$IP6TABLES_SAVE > $BACKUP_DIR/ip6tables.before.$TIMESTAMP"
    log "INFO" "ip6tables-restore futtatása a következő szabályok betöltésére:"
    log "===== ip6tables preview (ip6tables-restore input) ====="
    echo "$IP6_RENDERED" | sed 's/^/  /'
    log "APPLY COMPLETE: $SCRIPT_NAME sikeresen alkalmazva (DRY-RUN)."
    exit 0
fi

# ----------------------------------------------------
# APPLY FÁZIS
# ----------------------------------------------------

log "ACTION" "Kritikus fájlok előkészítése és backupja."
run mkdir -p "$BACKUP_DIR"
run cp -a "$SYSCTL_CONF" "$BACKUP_DIR/99-ipv6-worms.conf.bak" 2>/dev/null || true
run "$IP6TABLES_SAVE > $BACKUP_DIR/ip6tables.before.$TIMESTAMP"

# 1. Apply Sysctl
log "ACTION" "Writing sysctl config to $SYSCTL_CONF"
run echo "$SYSCONF" > "$SYSCTL_CONF"
run chmod 0644 "$SYSCTL_CONF"

log "ACTION" "Applying sysctl --system"
run sysctl --system # KRITIKUS JAVÍTÁS: Hibaelnyelés eltávolítva: set -e kezeli a hibát

# 2. Apply ip6tables rules via restore
log "ACTION" "Applying ip6tables rules via ip6tables-restore (rendered for $IFACE)"

TMP_RULES_FILE="/tmp/v6worm_ip6_apply_$TIMESTAMP.conf"
run echo "$IP6_RENDERED" > "$TMP_RULES_FILE"

if command -v $IP6TABLES_RESTORE >/dev/null 2>&1; then
    # KRITIKUS JAVÍTÁS: Hibaelnyelés eltávolítva: set -e kezeli a hibát
    run $IP6TABLES_RESTORE < "$TMP_RULES_FILE"
    log "OK" "ip6tables szabályok betöltve."
else
    log "FATAL" "ip6tables-restore not found. Rules were written to $TMP_RULES_FILE, de NEM alkalmazva!"
    exit 1
fi

run rm -f "$TMP_RULES_FILE"

# 3. Zárás és Lezárás (Commit)
log "COMMIT" "Kritikus fájlok lezárása (chattr +i)."
run chattr +i "$SYSCTL_CONF" # KRITIKUS JAVÍTÁS: Immutability lock

# 4. Persist rules
if command -v netfilter-persistent >/dev/null 2>&1; then
  log "ACTION" "Persisting rules with netfilter-persistent."
  run netfilter-persistent save || true
fi

# 5. Rollback fájl törlése
run rm -f "$BACKUP_DIR/99-ipv6-worms.conf.bak"

log "APPLY COMPLETE: IPv6 worm protections applied. Backups in: $BACKUP_DIR"
exit 0
