#!/bin/bash
# branches/03_sysctl_ip6tables-security.sh
# Sysctl hardening for kernel, BPF lockdown and IPv6 security.
# Usage: sudo ./03_sysctl_ip6tables-security.sh [--dry-run|--apply] [--iface IFACE]
# Author: Beatrix Zelezny 🐱
# Revision: 2025-10-20 (Refactored, --dry-run ready, WG removed)
set -euo pipefail

# --- CONFIG ---
SYSCTL_CONF="/etc/sysctl.d/99-security-ipv6.conf"
BACKUP_DIR="${BRANCH_BACKUP_DIR:-/var/backups/skell_backups/03_sysctl}"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"
IP6TABLES_BIN="/sbin/ip6tables"
IP6TABLES_SAVE="/sbin/ip6tables-save"

# --- DRY-RUN MÓD KEZELÉSE ---
DRY_RUN=true
IFACE=""

usage() {
  cat <<EOF
Usage: $0 [--iface IFACE] [--apply|--dry-run]
  --iface IFACE : Target interface (default: autodetect)
  --apply   : Apply configuration (writes sysctl + applies rules)
  --dry-run : Preview only (default)
EOF
  exit 1
}

while [ $# -gt 0 ]; do
  case "$1" in
    --iface) IFACE="$2"; shift 2;;
    --apply) DRY_RUN=false; shift;;
    --dry-run) DRY_RUN=true; shift;;
    -h|--help) usage;;
    *) echo "Unknown arg: $1"; usage;;
  esac
done

# --- HELPERS ---
log() { echo "$(date +%F' '%T) [03_SYSCTL] $*"; }
dry_run_log() {
    if $DRY_RUN; then
        log "[DRY-RUN] TENNÉ: $*"
    fi
}
# -----------------

log "START: IPv6 Hardening flow. Mode: $(if $DRY_RUN; then echo "DRY-RUN"; else echo "APPLY"; fi)"

# Pre-checks (Ezek dry-runban is futnak!)
[ "$(id -u)" -eq 0 ] || { echo "Run as root"; exit 2; }
mkdir -p "$BACKUP_DIR"

# autodetect IPv6 interface
if [ -z "$IFACE" ]; then
  log "[INFO] Autodetecting IPv6 interface..."
  IFACE=$(ip -6 route show default 2>/dev/null | awk '/default/ {for(i=1;i<=NF;i++) if ($i=="dev"){print $(i+1); exit}}')
  [ -z "$IFACE" ] && IFACE=$(ip -6 addr show scope global | awk '/inet6/ {iface=$2} /^[0-9]+:/ {gsub(":","",$2)} END{print iface}')
fi

if [ -z "$IFACE" ]; then
  log "[ERROR] Could not autodetect IPv6 interface. Use --iface manually."
  exit 3
fi

log "Target interface: $IFACE"


# --- SYSCTL BASELINE (includes kernel.unprivileged_bpf_disabled = 1) ---
read -r -d '' SYSCONF <<EOF || true
# Skell Core kernel and filesystem protections
kernel.dmesg_restrict = 1
kernel.kptr_restrict = 1
kernel.panic = 30
kernel.panic_on_oops = 1
kernel.modules_disabled = 1
kernel.unprivileged_bpf_disabled = 1
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
fs.protected_regular = 2
fs.protected_fifos = 2
fs.suid_dumpable = 0

# Virtual memory & performance tweaks
vm.mmap_min_addr = 65536
vm.swappiness = 10

# IPv6 Security baseline
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0
net.ipv6.conf.all.forwarding = 0
net.ipv6.conf.default.forwarding = 0

# Privacy addresses (RFC 4941)
net.ipv6.conf.all.use_tempaddr = 2
net.ipv6.conf.default.use_tempaddr = 2
net.ipv6.conf.$IFACE.use_tempaddr = 2

# Optional (commented to avoid breaking hotspot RA):
# net.ipv6.conf.all.accept_ra = 0
# net.ipv6.conf.$IFACE.accept_ra = 0

# ICMPv6 rate limit
net.ipv6.icmp.ratelimit = 100
EOF

# --- ip6tables baseline ruleset build (NO WireGuard) ---
build_ip6_rules() {
  cat <<'RULES'
# Generated by 03_sysctl_ip6tables-security.sh (Rules start)
*filter
__IP6__ -F
__IP6__ -X
__IP6__ -P INPUT DROP
__IP6__ -P FORWARD DROP
__IP6__ -P OUTPUT ACCEPT

# Loopback
__IP6__ -A INPUT -i lo -j ACCEPT

# Established connections
__IP6__ -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow ICMPv6 ND types (133-136)
for t in 133 134 135 136; do
  __IP6__ -A INPUT -p ipv6-icmp --icmpv6-type $t -m limit --limit 50/min -j ACCEPT
done

# Allow essential ICMPv6 (Error messages)
__IP6__ -A INPUT -p ipv6-icmp --icmpv6-type destination-unreachable -j ACCEPT
__IP6__ -A INPUT -p ipv6-icmp --icmpv6-type packet-too-big -j ACCEPT
__IP6__ -A INPUT -p ipv6-icmp --icmpv6-type time-exceeded -j ACCEPT
__IP6__ -A INPUT -p ipv6-icmp --icmpv6-type parameter-problem -j ACCEPT

# Allow Quad9 DNS out (04_dns_quad9.sh-ban is kell majd ellenőrizni!)
__IP6__ -A OUTPUT -o __IFACE__ -p udp -d 2620:fe::fe --dport 53 -j ACCEPT
__IP6__ -A OUTPUT -o __IFACE__ -p udp -d 2620:fe::9 --dport 53 -j ACCEPT
__IP6__ -A OUTPUT -o __IFACE__ -p tcp -d 2620:fe::fe --dport 53 -j ACCEPT
__IP6__ -A OUTPUT -o __IFACE__ -p tcp -d 2620:fe::9 --dport 53 -j ACCEPT

# Drop & log unknowns
__IP6__ -A INPUT -m limit --limit 3/min -j LOG --log-prefix "IP6DROP: "
__IP6__ -A INPUT -j DROP
COMMIT
# Generated by 03_sysctl_ip6tables-security.sh (Rules end)
RULES
}

IP6_RAW=$(build_ip6_rules)
IP6_RENDERED=$(echo "$IP6_RAW" | sed "s|__IP6__|$IP6TABLES_BIN|g" \
                                 | sed "s|__IFACE__|$IFACE|g")


# ----------------------------------------------------
# DRY-RUN FÁZIS: Logolja a TÉNYLEGES módosításokat
# ----------------------------------------------------
if $DRY_RUN; then
    log "START: SKELL 03_sysctl_ip6tables-security flow (DRY-RUN MODE)"

    dry_run_log "Sysctl konfiguráció kiírása a $SYSCTL_CONF fájlba (BPF lockdown + IPv6 hardening)."
    dry_run_log "sysctl --system parancs futtatása a változók betöltéséhez."

    dry_run_log "ip6tables szabályok mentése $BACKUP_DIR alá."
    dry_run_log "ip6tables szabályok futtatása ip6tables-restore paranccsal a következő szabályok szerint:"
    echo "$IP6_RENDERED" | dry_run_log "    <<< IP6TABLES RULES START >>>"
    echo "$IP6_RENDERED" | dry_run_log "    <<< IP6TABLES RULES END >>>"

    log "03_sysctl_ip6tables-security completed. (DRY-RUN) RC=0"
    exit 0
fi

# ----------------------------------------------------
# APPLY FÁZIS
# ----------------------------------------------------

log "[APPLY] Creating backups at $BACKUP_DIR"
cp -a "$SYSCTL_CONF" "$BACKUP_DIR/99-security-ipv6.conf.bak" 2>/dev/null || true
$IP6TABLES_SAVE > "$BACKUP_DIR/ip6tables.before.$TIMESTAMP" 2>/dev/null || true

# 1. Apply Sysctl
log "[ACTION] Writing sysctl config to $SYSCTL_CONF"
echo "$SYSCONF" > "$SYSCTL_CONF"

log "[ACTION] Applying sysctl --system"
sysctl --system || true

# 2. Apply ip6tables rules
log "[ACTION] Applying ip6tables rules (rendered for $IFACE)"

# Ideális esetben a rules.v6 fájlt írjuk, és ip6tables-restore-ral töltjük be.
# Ez idempotens és megbízhatóbb, mint a sok ip6tables parancs futtatása.
IP6TABLES_FILE="/etc/ip6tables/rules.v6"
mkdir -p "$(dirname "$IP6TABLES_FILE")"
echo "$IP6_RENDERED" > "$IP6TABLES_FILE"

if command -v ip6tables-restore >/dev/null 2>&1; then
    ip6tables-restore < "$IP6TABLES_FILE" || log "[WARN] ip6tables-restore failed."
    log "[OK] ip6tables szabályok betöltve a $IP6TABLES_FILE-ból."
else
    log "[WARN] ip6tables-restore nem található, szabályok csak a fájlba lettek írva."
fi


log "[DONE] IPv6 Hardening completed. RC=0"
exit 0
