#!/bin/bash
# 05_ipv6_worm_protection.sh
# IPv6 "v6worms" protection (sysctl + ip6tables)
# Implements mitigations inspired by Bellovin/Cheswick/Keromytis (v6 worm strategies).
# Zero Trust Principle: Removed all WireGuard support.
#
# Usage:
#   sudo ./05_ipv6_worm_protection.sh --dry-run [--iface IFACE] [--allow-ra]
#   sudo ./05_ipv6_worm_protection.sh --apply [--iface IFACE] [--allow-ra]
#
set -euo pipefail

# ---------- CONFIG ----------
SYSCTL_CONF="/etc/sysctl.d/99-ipv6-worms.conf"
IP6TABLES_BIN="/sbin/ip6tables"
IP6TABLES_SAVE="/sbin/ip6tables-save"
IP6TABLES_RESTORE="/sbin/ip6tables-restore"
BACKUP_DIR="${BRANCH_BACKUP_DIR:-/var/backups/skell_backups/05_ipv6worm}"
TIMESTAMP="$(date +%Y%m%d-%H%M%S)"

# --- DRY-RUN MÓD KEZELÉSE ---
DRY_RUN=true
IFACE=""
ALLOW_RA=false

# --- LOG ÉS HELPERS ---
log() { echo "$(date +%F' '%T) [05_IPV6WORM] $*"; }
dry_run_log() {
    if $DRY_RUN; then
        log "[DRY-RUN] TENNÉ: $*"
    fi
}

usage() {
  cat <<EOF
Usage: $0 [--iface IFACE] [--apply|--dry-run] [--allow-ra]
  --iface IFACE : target interface for per-interface sysctl rules (autodetected if omitted)
  --dry-run   : show planned changes (default)
  --apply     : make changes (writes sysctl + runs ip6tables-restore)
  --allow-ra  : allow accepting Router Advertisements on the IF (default: blocked for security)
EOF
  exit 1
}

# --- ARGUMENTUMOK FELDOLGOZÁSA ---
while [ $# -gt 0 ]; do
  case "$1" in
    --iface) IFACE="$2"; shift 2;;
    --apply) DRY_RUN=false; shift;;
    --dry-run) DRY_RUN=true; shift;;
    --allow-ra) ALLOW_RA=true; shift;;
    -h|--help) usage;;
    *) log "[ERROR] Unknown arg: $1"; usage;;
  esac
done

# root check
[ "$(id -u)" -eq 0 ] || { echo "Run as root"; exit 2; }

# autodetect interface
log "START: IPv6 Worm Protection Flow. Mode: $(if $DRY_RUN; then echo "DRY-RUN"; else echo "APPLY"; fi)"

if [ -z "$IFACE" ]; then
  log "[INFO] Autodetecting IPv6 interface..."
  IFACE=$(ip -6 route show default 2>/dev/null | awk '/default/ {for(i=1;i<=NF;i++) if ($i=="dev") {print $(i+1); exit}}' || true)
  if [ -z "$IFACE" ]; then
    IFACE=$(ip -6 addr show scope global | awk '/^[0-9]+:/{iface=$2} /inet6/ && /scope global/ {gsub(/:$/,"",iface); print iface; exit}')
  fi
fi

if [ -z "$IFACE" ]; then
  log "[ERROR] Could not autodetect IPv6 interface. Pass --iface IFACE manually." >&2
  exit 3
fi

log "Target interface: $IFACE"
log "Router Advertisements (RA) Status: $( $ALLOW_RA && echo ALLOWED || echo BLOCKED ) (via sysctl)"


# ---------- Build sysctl content ----------
read -r -d '' SYSCONF_CORE <<'EOF' || true
# IPv6 worm protection sysctl (generated by 05_ipv6_worm_protection.sh)
# Global kernel hardening
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0
net.ipv6.conf.all.forwarding = 0
net.ipv6.conf.default.forwarding = 0
# limit ICMPv6 (kernel-level ratelimiting where available)
net.ipv6.icmp.ratelimit = 100
# protect ND tables a bit (not perfect but helpful)
net.ipv6.neigh.default.gc_thresh1 = 128
net.ipv6.neigh.default.gc_thresh2 = 512
net.ipv6.neigh.default.gc_thresh3 = 1024
# filesystem / kernel protections (useful generally)
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
kernel.dmesg_restrict = 1
kernel.kptr_restrict = 1
EOF

SYSCONF="$SYSCONF_CORE"$'\n'
# Add per-interface choices for RA/autoconf depending on --allow-ra
if $ALLOW_RA; then
  SYSCONF="$SYSCONF"$'\n'"# Allow RA on $IFACE (explicit because --allow-ra passed)"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.accept_ra = 1"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.autoconf = 1"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.accept_ra_defrtr = 1"
else
  SYSCONF="$SYSCONF"$'\n'"# Block Router Advertisements and autoconf on $IFACE by default (safer mitigation)"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.accept_ra = 0"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.autoconf = 0"
  SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.accept_ra_defrtr = 0"
fi

# Additional per-interface privacy/enforcement
SYSCONF="$SYSCONF"$'\n'"# Prefer temporary (privacy) addresses on IF"
SYSCONF="$SYSCONF"$'\n'"net.ipv6.conf.$IFACE.use_tempaddr = 2"


# ---------- Build ip6tables rule set (Restore syntax) ----------
build_ip6_rules() {
  cat <<'RULES'
# Generated by 05_ipv6_worm_protection.sh
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]

# Loopback
-A INPUT -i lo -j ACCEPT

# Established connections
-A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow Neighbor Discovery ICMPv6 types (rate-limited)
-A INPUT -p ipv6-icmp --icmpv6-type 133 -m limit --limit 30/min -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type 134 -m limit --limit 30/min -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type 135 -m limit --limit 100/min -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type 136 -m limit --limit 100/min -j ACCEPT

# Allow essential ICMPv6 error messages
-A INPUT -p ipv6-icmp --icmpv6-type destination-unreachable -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type packet-too-big -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type time-exceeded -j ACCEPT
-A INPUT -p ipv6-icmp --icmpv6-type parameter-problem -j ACCEPT

# Block non-ND multicast traffic arriving to the interface (drop other ff00::/8)
-A INPUT -d ff00::/8 -i __IFACE__ -p ! ipv6-icmp -j DROP

# Allow DNS to Quad9 (via interface, for fallbacks or external queries)
-A OUTPUT -o __IFACE__ -p udp -d 2620:fe::fe --dport 53 -j ACCEPT
-A OUTPUT -o __IFACE__ -p tcp -d 2620:fe::fe --dport 53 -j ACCEPT
-A OUTPUT -o __IFACE__ -p udp -d 2620:fe::9 --dport 53 -j ACCEPT
-A OUTPUT -o __IFACE__ -p tcp -d 2620:fe::9 --dport 53 -j ACCEPT

# Log a small amount and drop the rest
-A INPUT -m limit --limit 5/min -j LOG --log-prefix "V6WORMDROP: "
-A INPUT -j DROP
COMMIT
RULES
}

IP6_RAW=$(build_ip6_rules)
IP6_RENDERED=$(printf "%s" "$IP6_RAW" | sed "s|__IFACE__|$IFACE|g")


# ----------------------------------------------------
# DRY-RUN FÁZIS
# ----------------------------------------------------
if $DRY_RUN; then
    log "START: SKELL 05_ipv6_worm_protection.sh flow (DRY-RUN MODE)"

    dry_run_log "Sysctl konfiguráció kiírása a $SYSCTL_CONF fájlba (IPv6 worm mitigation + kernel hardening)."
    log "===== SYSCTL (will be written to: $SYSCTL_CONF) ====="
    echo "$SYSCONF" | sed 's/^/  /'
    dry_run_log "sysctl --system parancs futtatása a változók betöltéséhez."

    dry_run_log "ip6tables szabályok mentése $BACKUP_DIR alá."
    dry_run_log "ip6tables-restore futtatása a következő szabályok betöltésére:"
    log "===== ip6tables preview (ip6tables-restore input) ====="
    echo "$IP6_RENDERED" | sed 's/^/  /'
    log "05_ipv6_worm_protection.sh completed. (DRY-RUN) RC=0"
    exit 0
fi

# ----------------------------------------------------
# APPLY FÁZIS
# ----------------------------------------------------

log "[APPLY] Creating backups at $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"
cp -a "$SYSCTL_CONF" "$BACKUP_DIR/99-ipv6-worms.conf.bak" 2>/dev/null || true
$IP6TABLES_SAVE > "$BACKUP_DIR/ip6tables.before.$TIMESTAMP" 2>/dev/null || true

# 1. Apply Sysctl
log "[ACTION] Writing sysctl config to $SYSCTL_CONF"
echo "$SYSCONF" > "$SYSCTL_CONF"
chmod 0644 "$SYSCTL_CONF"

log "[ACTION] Applying sysctl --system"
sysctl --system || log "[WARN] sysctl --system returned non-zero, check manually."

# 2. Apply ip6tables rules via restore
log "[ACTION] Applying ip6tables rules via ip6tables-restore (rendered for $IFACE)"

TMP_RULES_FILE="/tmp/v6worm_ip6_apply_$TIMESTAMP.conf"
echo "$IP6_RENDERED" > "$TMP_RULES_FILE"

if command -v $IP6TABLES_RESTORE >/dev/null 2>&1; then
    $IP6TABLES_RESTORE < "$TMP_RULES_FILE" || log "[WARN] ip6tables-restore failed. Check syntax or permissions."
    log "[OK] ip6tables szabályok betöltve."
else
    log "[WARN] ip6tables-restore not found. Rules were written to $TMP_RULES_FILE, but NOT applied."
fi

rm -f "$TMP_RULES_FILE"

# 3. Persist rules
if command -v netfilter-persistent >/dev/null 2>&1; then
  log "[ACTION] Persisting rules with netfilter-persistent."
  netfilter-persistent save || true
fi

log "[APPLY COMPLETE] IPv6 worm protections applied. Backups in: $BACKUP_DIR"
exit 0
